### ISSUE TITLE
Why doesn't Dart2 work?

### ISSUE THREAD

**Issue by guoyuanzhuang** [Jaguar-dart/ninja#3]
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because flutter_app depends on ninja any which requires SDK version >=2.0.0-dev.60.0 <2.0.0, version solving failed.

pub get failed (1)

**Comment by tejainece** [comment]
It hasn't been upgraded to Dart 2 yet. Will do it.

**Comment by tejainece** [comment]
Fixed.
